output.elf:
  rules: semu_rule.txt
  enable_native: false
  emulate_mode: emulate
  loop_whitelist:
  - memset
  - memcpy
  - memmove
  - FillZerobss
  - LoopFillZerobss
  - CopyDataInit
  - LoopCopyDataInit
  - Zero_Init
  - Reset_Handler
  - SystemInit
  handlers:
    Delay: do_return
    HAL_Delay: do_return
    wait: do_return
    wait_us: do_return
    HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
    HAL_BE_In: fuzzemu.handlers.common.hal_in
    HAL_BE_Out: fuzzemu.handlers.common.hal_out
    HAL_BE_return_0: fuzzemu.handlers.common.return_zero
    HAL_BE_return_1: fuzzemu.handlers.common.return_true
    HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
    HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
    puts: do_return
    fflush: do_return
    DP83848_Init: do_return
    stm32_putc: do_return
    rt_thread_mdelay: do_return
    DelayLoop: do_return
    SDK_DelayAtLeastUs: do_return
    LPUART_WriteBlocking: do_return
    ENET_SetSMI: do_return
    DP83848_GetLinkState: fuzzemu.handlers.common.return_2
    PHY_GetLinkStatus: fuzzemu.handlers.common.return_2
    PHY_GetLinkSpeedDuplex: fuzzemu.handlers.common.return_2
    HAL_RCC_ClockConfig: fuzzemu.handlers.common.return_zero
    HAL_ETH_ReadPHYRegister: fuzzemu.handlers.common.return_zero
    ethernetif_phy_init: fuzzemu.handlers.common.return_zero
    PHY_Init: fuzzemu.handlers.common.return_zero
    ENET_MDIORead: fuzzemu.handlers.common.return_phy_id
  mmio_funcs:
  - add_to_waitq_locked
  - adjust_owner_prio
  - arch_new_thread
  - dfll_init
  - dpll_init
  - encode_float
  - first
  - gclk_connect
  - gclk_reset
  - halt_thread
  - init_ready_q
  - k_heap_init
  - k_mbox_get
  - k_mbox_init
  - k_mem_slab_init
  - k_msgq_cleanup
  - k_msgq_init
  - k_stack_cleanup
  - k_stack_init
  - k_timer_init
  - k_work_cancel_delayable_sync
  - k_work_cancel_sync
  - k_work_flush
  - k_work_flush_delayable
  - k_work_init_delayable
  - k_work_queue_start
  - mbox_message_put
  - move_thread_to_end_of_prio_q
  - next
  - osc32k_init
  - ready_thread
  - remove_timeout
  - sam0_eic_acquire
  - sam0_eic_disable_interrupt
  - sam0_eic_enable_interrupt
  - sam0_eic_init
  - sam0_eic_interrupt_pending
  - sam0_eic_isr
  - sam0_eic_release
  - timeout_rem
  - uart_sam0_init
  - update_cache
  - wait_synchronization
  - z_abort_timeout
  - z_add_timeout
  - z_arm_platform_init
  - z_cbvprintf_impl
  - z_impl_k_condvar_init
  - z_impl_k_mutex_init
  - z_impl_k_mutex_lock
  - z_impl_k_queue_init
  - z_impl_k_sem_init
  - z_impl_k_timer_status_sync
  - z_impl_k_yield
  - z_init_thread_base
  - z_priq_dumb_best
  - z_priq_dumb_remove
  - z_priq_mq_best
  - z_sched_waitq_walk
  - z_set_prio
  - z_setup_new_thread
  - z_timer_expiration_handler
  - z_unpend_all
