output.elf:
  rules: semu_rule.txt
  enable_native: false
  emulate_mode: emulate
  loop_whitelist:
  - memset
  - memcpy
  - memmove
  - Reset_Handler
  - SystemInit
  - SystemInitHook
  - LoopCopyDataInit
  - LoopFillZerobss
  - CopyDataInit
  - FillZerobss
  handlers:
    Delay: do_return
    HAL_Delay: do_return
    wait: do_return
    wait_us: do_return
    HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
    HAL_BE_In: fuzzemu.handlers.common.hal_in
    HAL_BE_Out: fuzzemu.handlers.common.hal_out
    HAL_BE_return_0: fuzzemu.handlers.common.return_zero
    HAL_BE_return_1: fuzzemu.handlers.common.return_true
    HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
    HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
  mmio_funcs:
  - imxrt_isr
  - CLOCK_InitEnetPll
  - CLOCK_InitVideoPll
  - CLOCK_InitAudioPll
  - CLOCK_InitUsb2Pll
  - CLOCK_InitUsb1Pll
  - CLOCK_InitSysPll
  - CLOCK_InitArmPll
  - ENET_SetMacController
  - BOARD_BootClockRUN
  - BOARD_ReconfigFlexSpiRxBuffer
  - ENET_TransmitIRQHandler
  - CLOCK_SetDiv
  - CLOCK_SetMux
  - ENET_ReceiveIRQHandler
  - ENET_GetInstance
  - GPIO_GetInstance
  - ENET_LeaveMulticastGroup
  - ENET_AddMulticastGroup
  - ENET_GetRxFrame
  - CLOCK_InitExternalClk
