output.elf:
  rules: semu_rule.txt
  enable_native: false
  emulate_mode: emulate
  loop_whitelist:
  - memset
  - memcpy
  - memmove
  - FillZerobss
  - LoopFillZerobss
  - CopyDataInit
  - LoopCopyDataInit
  - Zero_Init
  - Reset_Handler
  - SystemInit
  handlers:
    Delay: do_return
    HAL_Delay: do_return
    wait: do_return
    wait_us: do_return
    HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
    HAL_BE_In: fuzzemu.handlers.common.hal_in
    HAL_BE_Out: fuzzemu.handlers.common.hal_out
    HAL_BE_return_0: fuzzemu.handlers.common.return_zero
    HAL_BE_return_1: fuzzemu.handlers.common.return_true
    HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
    HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
    puts: do_return
    fflush: do_return
    DP83848_Init: do_return
    stm32_putc: do_return
    rt_thread_mdelay: do_return
    DelayLoop: do_return
    SDK_DelayAtLeastUs: do_return
    LPUART_WriteBlocking: do_return
    ENET_SetSMI: do_return
    DP83848_GetLinkState: fuzzemu.handlers.common.return_2
    PHY_GetLinkStatus: fuzzemu.handlers.common.return_2
    PHY_GetLinkSpeedDuplex: fuzzemu.handlers.common.return_2
    HAL_RCC_ClockConfig: fuzzemu.handlers.common.return_zero
    HAL_ETH_ReadPHYRegister: fuzzemu.handlers.common.return_zero
    ethernetif_phy_init: fuzzemu.handlers.common.return_zero
    PHY_Init: fuzzemu.handlers.common.return_zero
    ENET_MDIORead: fuzzemu.handlers.common.return_phy_id
  mmio_funcs:
  - BSP_COM_Init
  - BSP_LED_Init
  - BSP_PB_Init
  - EEPROM_IO_ReadData
  - EEPROM_IO_WriteData
  - FLASH_Erase_Sector
  - FLASH_FlushCaches
  - FLASH_MassErase
  - FLASH_OB_GetUser
  - FLASH_Program_Byte
  - FLASH_Program_DoubleWord
  - FLASH_Program_HalfWord
  - FLASH_Program_Word
  - FLASH_SetErrorCode
  - FLASH_WaitForLastOperation
  - FSMC_BANK3_MspInit
  - FSMC_BANK3_ReadData
  - FSMC_BANK3_WriteData
  - FSMC_BANK3_WriteReg
  - FSMC_NORSRAM_DeInit
  - FSMC_NORSRAM_Extended_Timing_Init
  - FSMC_NORSRAM_Init
  - FSMC_NORSRAM_Timing_Init
  - FSMC_NORSRAM_WriteOperation_Disable
  - FSMC_NORSRAM_WriteOperation_Enable
  - HAL_DeInit
  - HAL_FLASHEx_Erase
  - HAL_FLASHEx_Erase_IT
  - HAL_FLASH_IRQHandler
  - HAL_FLASH_Lock
  - HAL_FLASH_OB_Lock
  - HAL_FLASH_OB_Unlock
  - HAL_FLASH_Program
  - HAL_FLASH_Program_IT
  - HAL_FLASH_Unlock
  - HAL_GPIO_DeInit
  - HAL_GPIO_EXTI_IRQHandler
  - HAL_GPIO_Init
  - HAL_GPIO_LockPin
  - HAL_GPIO_ReadPin
  - HAL_GPIO_TogglePin
  - HAL_GPIO_WritePin
  - HAL_HalfDuplex_EnableReceiver
  - HAL_HalfDuplex_EnableTransmitter
  - HAL_HalfDuplex_Init
  - HAL_I2C_DeInit
  - HAL_I2C_DisableListen_IT
  - HAL_I2C_ER_IRQHandler
  - HAL_I2C_EV_IRQHandler
  - HAL_I2C_EnableListen_IT
  - HAL_I2C_Init
  - HAL_I2C_IsDeviceReady
  - HAL_I2C_Master_Abort_IT
  - HAL_I2C_Master_Receive
  - HAL_I2C_Master_Receive_DMA
  - HAL_I2C_Master_Receive_IT
  - HAL_I2C_Master_Seq_Receive_DMA
  - HAL_I2C_Master_Seq_Receive_IT
  - HAL_I2C_Master_Seq_Transmit_DMA
  - HAL_I2C_Master_Seq_Transmit_IT
  - HAL_I2C_Master_Transmit
  - HAL_I2C_Master_Transmit_DMA
  - HAL_I2C_Master_Transmit_IT
  - HAL_I2C_Mem_Read
  - HAL_I2C_Mem_Read_DMA
  - HAL_I2C_Mem_Read_IT
  - HAL_I2C_Mem_Write
  - HAL_I2C_Mem_Write_DMA
  - HAL_I2C_Mem_Write_IT
  - HAL_I2C_Slave_Receive
  - HAL_I2C_Slave_Receive_DMA
  - HAL_I2C_Slave_Receive_IT
  - HAL_I2C_Slave_Seq_Receive_DMA
  - HAL_I2C_Slave_Seq_Receive_IT
  - HAL_I2C_Slave_Seq_Transmit_DMA
  - HAL_I2C_Slave_Seq_Transmit_IT
  - HAL_I2C_Slave_Transmit
  - HAL_I2C_Slave_Transmit_DMA
  - HAL_I2C_Slave_Transmit_IT
  - HAL_Init
  - HAL_LIN_Init
  - HAL_LIN_SendBreak
  - HAL_MultiProcessor_EnterMuteMode
  - HAL_MultiProcessor_ExitMuteMode
  - HAL_MultiProcessor_Init
  - HAL_RCC_ClockConfig
  - HAL_RCC_GetClockConfig
  - HAL_RCC_GetPCLK1Freq
  - HAL_RCC_GetPCLK2Freq
  - HAL_RCC_MCOConfig
  - HAL_RCC_NMI_IRQHandler
  - HAL_SRAM_Init
  - HAL_SRAM_Read_DMA
  - HAL_SRAM_Write_DMA
  - HAL_UARTEx_ReceiveToIdle
  - HAL_UARTEx_ReceiveToIdle_DMA
  - HAL_UARTEx_ReceiveToIdle_IT
  - HAL_UART_Abort
  - HAL_UART_AbortReceive
  - HAL_UART_AbortReceive_IT
  - HAL_UART_AbortTransmit
  - HAL_UART_AbortTransmit_IT
  - HAL_UART_Abort_IT
  - HAL_UART_DMAPause
  - HAL_UART_DMAResume
  - HAL_UART_DMAStop
  - HAL_UART_DeInit
  - HAL_UART_IRQHandler
  - HAL_UART_Init
  - HAL_UART_Receive
  - HAL_UART_Receive_DMA
  - HAL_UART_Receive_IT
  - HAL_UART_Transmit
  - HAL_UART_Transmit_DMA
  - HAL_UART_Transmit_IT
  - I2C_DMAAbort
  - I2C_DMAError
  - I2C_DMAXferCplt
  - I2C_Flush_DR
  - I2C_ITError
  - I2C_IsAcknowledgeFailed
  - I2C_MasterReceive_BTF
  - I2C_MasterReceive_RXNE
  - I2C_MasterRequestRead
  - I2C_MasterRequestWrite
  - I2C_MasterTransmit_BTF
  - I2C_MasterTransmit_TXE
  - I2C_Master_ADD10
  - I2C_Master_ADDR
  - I2C_Master_SB
  - I2C_MemoryTransmit_TXE_BTF
  - I2C_RequestMemoryRead
  - I2C_RequestMemoryWrite
  - I2C_SlaveReceive_BTF
  - I2C_SlaveReceive_RXNE
  - I2C_SlaveTransmit_BTF
  - I2C_SlaveTransmit_TXE
  - I2C_Slave_ADDR
  - I2C_Slave_AF
  - I2C_Slave_STOPF
  - I2C_WaitOnBTFFlagUntilTimeout
  - I2C_WaitOnFlagUntilTimeout
  - I2C_WaitOnMasterAddressFlagUntilTimeout
  - I2C_WaitOnRXNEFlagUntilTimeout
  - I2C_WaitOnSTOPFlagUntilTimeout
  - I2C_WaitOnSTOPRequestThroughIT
  - I2C_WaitOnTXEFlagUntilTimeout
  - I2Cx_ITConfig
  - I2Cx_MspInit
  - I2Cx_Read
  - I2Cx_ReadMultiple
  - I2Cx_Write
  - I2Cx_WriteMultiple
  - IOE_ReadMultiple
  - LCD_IO_WriteMultipleData
  - SystemClock_Config
  - SystemCoreClockUpdate
  - SystemInit
  - UART_DMAError
  - UART_DMAReceiveCplt
  - UART_DMATransmitCplt
  - UART_EndRxTransfer
  - UART_EndTransmit_IT
  - UART_EndTxTransfer
  - UART_Receive_IT
  - UART_SetConfig
  - UART_Start_Receive_DMA
  - UART_Start_Receive_IT
  - UART_Transmit_IT
  - UART_WaitOnFlagUntilTimeout
