output.elf:
  rules: semu_rule.txt
  enable_native: false
  emulate_mode: emulate
  loop_whitelist:
  - memset
  - memcpy
  - memmove
  - FillZerobss
  - LoopFillZerobss
  - CopyDataInit
  - LoopCopyDataInit
  - Zero_Init
  - Reset_Handler
  - SystemInit
  handlers:
    Delay: do_return
    HAL_Delay: do_return
    wait: do_return
    wait_us: do_return
    HAL_BE_ENET_ReadFrame: fuzzemu.handlers.common.hal_read_frame
    HAL_BE_In: fuzzemu.handlers.common.hal_in
    HAL_BE_Out: fuzzemu.handlers.common.hal_out
    HAL_BE_return_0: fuzzemu.handlers.common.return_zero
    HAL_BE_return_1: fuzzemu.handlers.common.return_true
    HAL_BE_Block_Read: fuzzemu.handlers.common.hal_block_in
    HAL_BE_Block_Write: fuzzemu.handlers.common.hal_block_out
    puts: do_return
    fflush: do_return
    DP83848_Init: do_return
    stm32_putc: do_return
    rt_thread_mdelay: do_return
    DelayLoop: do_return
    SDK_DelayAtLeastUs: do_return
    LPUART_WriteBlocking: do_return
    ENET_SetSMI: do_return
    DP83848_GetLinkState: fuzzemu.handlers.common.return_2
    PHY_GetLinkStatus: fuzzemu.handlers.common.return_2
    PHY_GetLinkSpeedDuplex: fuzzemu.handlers.common.return_2
    HAL_RCC_ClockConfig: fuzzemu.handlers.common.return_zero
    HAL_ETH_ReadPHYRegister: fuzzemu.handlers.common.return_zero
    ethernetif_phy_init: fuzzemu.handlers.common.return_zero
    PHY_Init: fuzzemu.handlers.common.return_zero
    ENET_MDIORead: fuzzemu.handlers.common.return_phy_id
  mmio_funcs:
  - BOARD_BootClockRUN
  - BOARD_BootClockRUN_528M
  - BOARD_DebugConsoleSrcFreq
  - BOARD_InitPins
  - CLOCK_DeinitArmPll
  - CLOCK_DeinitAudioPll
  - CLOCK_DeinitEnetPll
  - CLOCK_DeinitExternalClk
  - CLOCK_DeinitRcOsc24M
  - CLOCK_DeinitSysPfd
  - CLOCK_DeinitSysPll
  - CLOCK_DeinitUsb1Pfd
  - CLOCK_DeinitUsb1Pll
  - CLOCK_DeinitUsb2Pll
  - CLOCK_DeinitVideoPll
  - CLOCK_DisableUsbhs0PhyPllClock
  - CLOCK_DisableUsbhs1PhyPllClock
  - CLOCK_EnableUsbhs0Clock
  - CLOCK_EnableUsbhs0PhyPllClock
  - CLOCK_EnableUsbhs1Clock
  - CLOCK_EnableUsbhs1PhyPllClock
  - CLOCK_GetAhbFreq
  - CLOCK_GetClockOutCLKO1Freq
  - CLOCK_GetClockOutClkO2Freq
  - CLOCK_GetFreq
  - CLOCK_GetIpgFreq
  - CLOCK_GetPerClkFreq
  - CLOCK_GetPeriphClkFreq
  - CLOCK_GetPllFreq
  - CLOCK_GetPllUsb1SWFreq
  - CLOCK_GetSemcFreq
  - CLOCK_GetSysPfdFreq
  - CLOCK_GetUsb1PfdFreq
  - CLOCK_InitArmPll
  - CLOCK_InitAudioPll
  - CLOCK_InitEnetPll
  - CLOCK_InitExternalClk
  - CLOCK_InitRcOsc24M
  - CLOCK_InitSysPfd
  - CLOCK_InitSysPll
  - CLOCK_InitUsb1Pfd
  - CLOCK_InitUsb1Pll
  - CLOCK_InitUsb2Pll
  - CLOCK_InitVideoPll
  - CLOCK_IsSysPfdEnabled
  - CLOCK_IsUsb1PfdEnabled
  - CLOCK_SetClockOutput1
  - CLOCK_SetClockOutput2
  - CLOCK_SwitchOsc
  - DCDC_Deinit
  - DCDC_Init
  - GPIO_PinInit
  - HAL_UartReceiveBlocking
  - HAL_UartSendBlocking
  - LPUART_ClearStatusFlags
  - LPUART_Deinit
  - LPUART_DisableInterrupts
  - LPUART_Enable9bitMode
  - LPUART_EnableInterrupts
  - LPUART_GetEnabledInterrupts
  - LPUART_GetStatusFlags
  - LPUART_Init
  - LPUART_RTOS_Init
  - LPUART_RTOS_Receive
  - LPUART_RTOS_Send
  - LPUART_ReadBlocking
  - LPUART_ReadBlocking16bit
  - LPUART_ReadNonBlocking
  - LPUART_ReadNonBlocking16bit
  - LPUART_SendAddress
  - LPUART_SetBaudRate
  - LPUART_TransferAbortReceive
  - LPUART_TransferAbortSend
  - LPUART_TransferCreateHandle
  - LPUART_TransferGetSendCount
  - LPUART_TransferHandleIDLEReady
  - LPUART_TransferHandleIRQ
  - LPUART_TransferHandleReceiveDataFull
  - LPUART_TransferHandleSendDataEmpty
  - LPUART_TransferHandleTransmissionComplete
  - LPUART_TransferReceiveNonBlocking
  - LPUART_TransferSendNonBlocking
  - LPUART_TransferStartRingBuffer
  - LPUART_TransferStopRingBuffer
  - LPUART_WaitForReadData
  - LPUART_WriteBlocking
  - LPUART_WriteBlocking16bit
  - LPUART_WriteNonBlocking
  - LPUART_WriteNonBlocking16bit
  - SystemCoreClockUpdate
  - SystemInit
  - uart_task
